name: Reset dev cache
on:
  delete:
    branches:
      - cs
      - st
      - tt
      - rt
jobs:
  test-delete-branch:
    name: Test delete branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Echo
        run: |
          echo "runner.os: ${{ runner.os }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "github.sha: ${{ github.sha }}"
