name: Reset dev cache
on:
  push:
    branches:
      - st
jobs:
  test-delete-branch:
    name: Test delete branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}

      - name: Echo
        run: |
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "github.event.ref_type: ${{ github.event.ref_type }}"
          echo "runner.os: ${{ runner.os }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "github.sha: ${{ github.sha }}"
